version: '3.8'

services:
  app:
    image: ko.local/kosample:latest
    ports:
      - 8080:8080
    environment: 
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kosample
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kosample
    healthcheck: 
      test: "psql -U postgres"
      interval: 1s
      timeout: 3s
      retries: 100
      start_period: 2s
    ports:
      - 5432:5432
